CREATE DATABASE web_scraper;

CREATE TABLE posts (
    id BIGSERIAL NOT NULL PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    loc VARCHAR(150) NOT NULL
);

CREATE TABLE imgs (
    img_id BIGSERIAL NOT NULL PRIMARY KEY,
    post_id BIGSERIAL NOT NULL REFERENCES posts(id),
    img_url VARCHAR(300) NOT NULL
);


