version: "3.8"
services:
  db:
    image: postgres
    ports:
      - "${PGPORT}:${PGPORT}"
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    volumes:
      - /pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: -p ${PGPORT}

  api:
    build: ./server
    ports:
      - "${APIPORT}:${APIPORT}"
    depends_on:
      - db

  client:
    build: ./client
    ports:
      - "${CLIENTPORT}:3000"
    depends_on:
      - api
